[package]
name = "nvd-yew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
web-sys = { version = "0.3.63", features = [
    "console",
    "Document",
    "Element",
    "Node",
    "Window",
    "HtmlButtonElement", ] }
wasm-bindgen = { version = "0.2.87", features = ["serde"] }
cvss = { path = "../cvss" }
cve = { path = "../cve" }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
js-sys = "0.3.64"
reqwest = { version = "0.11", features = ["json", "cookies"] }
serde = "1"
thiserror = "1.0"
wasm-bindgen-futures = "0.4.37"