name: Docker Publish
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      deploy_to_fly:
        description: '[Auto Fly Deploy]'
        required: false
        type: boolean
        default: false
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push nvd
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nvd-rs:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nvd-rs:latest
          cache-to: type=inline
      - name: Build and push helper
        uses: docker/build-push-action@v5
        with:
          context: .
          file: DockerfileHelper
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nvd-helper-rs:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nvd-helper-rs:latest
          cache-to: type=inline
  deploy:
    if: inputs.deploy_to_fly
    uses: ./.github/workflows/fly.yml
    needs:
      - docker
    secrets: inherit
